// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.1
// source: pkg/k8sservice/protocol.proto

package k8sservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crd   string `protobuf:"bytes,1,opt,name=crd,proto3" json:"crd,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CrdReply) Reset() {
	*x = CrdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrdReply) ProtoMessage() {}

func (x *CrdReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrdReply.ProtoReflect.Descriptor instead.
func (*CrdReply) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *CrdReply) GetCrd() string {
	if x != nil {
		return x.Crd
	}
	return ""
}

func (x *CrdReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetPodContainersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Containers []string `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	Error      string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetPodContainersReply) Reset() {
	*x = GetPodContainersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPodContainersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodContainersReply) ProtoMessage() {}

func (x *GetPodContainersReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodContainersReply.ProtoReflect.Descriptor instead.
func (*GetPodContainersReply) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *GetPodContainersReply) GetContainers() []string {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *GetPodContainersReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDescribeForReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Describe string `protobuf:"bytes,1,opt,name=describe,proto3" json:"describe,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetDescribeForReply) Reset() {
	*x = GetDescribeForReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDescribeForReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDescribeForReply) ProtoMessage() {}

func (x *GetDescribeForReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDescribeForReply.ProtoReflect.Descriptor instead.
func (*GetDescribeForReply) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *GetDescribeForReply) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *GetDescribeForReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PodLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodRawJson string `protobuf:"bytes,1,opt,name=pod_raw_json,json=podRawJson,proto3" json:"pod_raw_json,omitempty"`
	Container  string `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
}

func (x *PodLogRequest) Reset() {
	*x = PodLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodLogRequest) ProtoMessage() {}

func (x *PodLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodLogRequest.ProtoReflect.Descriptor instead.
func (*PodLogRequest) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *PodLogRequest) GetPodRawJson() string {
	if x != nil {
		return x.PodRawJson
	}
	return ""
}

func (x *PodLogRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type AllNamespacesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespaces []string `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Error      string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AllNamespacesReply) Reset() {
	*x = AllNamespacesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllNamespacesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllNamespacesReply) ProtoMessage() {}

func (x *AllNamespacesReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllNamespacesReply.ProtoReflect.Descriptor instead.
func (*AllNamespacesReply) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *AllNamespacesReply) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *AllNamespacesReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GvrReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *unstructured.UnstructuredList json
	UnstructuredListJson string `protobuf:"bytes,1,opt,name=unstructured_list_json,json=unstructuredListJson,proto3" json:"unstructured_list_json,omitempty"`
	Error                string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GvrReply) Reset() {
	*x = GvrReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GvrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GvrReply) ProtoMessage() {}

func (x *GvrReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GvrReply.ProtoReflect.Descriptor instead.
func (*GvrReply) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *GvrReply) GetUnstructuredListJson() string {
	if x != nil {
		return x.UnstructuredListJson
	}
	return ""
}

func (x *GvrReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchGvrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	G  string `protobuf:"bytes,1,opt,name=g,proto3" json:"g,omitempty"`
	V  string `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
	R  string `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	Ns string `protobuf:"bytes,4,opt,name=ns,proto3" json:"ns,omitempty"`
}

func (x *FetchGvrRequest) Reset() {
	*x = FetchGvrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchGvrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchGvrRequest) ProtoMessage() {}

func (x *FetchGvrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchGvrRequest.ProtoReflect.Descriptor instead.
func (*FetchGvrRequest) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *FetchGvrRequest) GetG() string {
	if x != nil {
		return x.G
	}
	return ""
}

func (x *FetchGvrRequest) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *FetchGvrRequest) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *FetchGvrRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

// v1.APIResourceList json string
type ApiResourceList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiResourceListJson string `protobuf:"bytes,1,opt,name=api_resource_list_json,json=apiResourceListJson,proto3" json:"api_resource_list_json,omitempty"`
}

func (x *ApiResourceList) Reset() {
	*x = ApiResourceList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiResourceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResourceList) ProtoMessage() {}

func (x *ApiResourceList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResourceList.ProtoReflect.Descriptor instead.
func (*ApiResourceList) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResourceList) GetApiResourceListJson() string {
	if x != nil {
		return x.ApiResourceListJson
	}
	return ""
}

type ApiResourceEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVer string `protobuf:"bytes,1,opt,name=api_ver,json=apiVer,proto3" json:"api_ver,omitempty"`
	Gv     string `protobuf:"bytes,2,opt,name=gv,proto3" json:"gv,omitempty"`
	// v1.APIResource
	ApiResourceJson string `protobuf:"bytes,3,opt,name=api_resource_json,json=apiResourceJson,proto3" json:"api_resource_json,omitempty"`
	Schema          string `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *ApiResourceEntry) Reset() {
	*x = ApiResourceEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiResourceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResourceEntry) ProtoMessage() {}

func (x *ApiResourceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResourceEntry.ProtoReflect.Descriptor instead.
func (*ApiResourceEntry) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResourceEntry) GetApiVer() string {
	if x != nil {
		return x.ApiVer
	}
	return ""
}

func (x *ApiResourceEntry) GetGv() string {
	if x != nil {
		return x.Gv
	}
	return ""
}

func (x *ApiResourceEntry) GetApiResourceJson() string {
	if x != nil {
		return x.ApiResourceJson
	}
	return ""
}

func (x *ApiResourceEntry) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type ApiResourceInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cached              bool              `protobuf:"varint,1,opt,name=cached,proto3" json:"cached,omitempty"`
	ApiResourceListJson []string          `protobuf:"bytes,2,rep,name=api_resource_list_json,json=apiResourceListJson,proto3" json:"api_resource_list_json,omitempty"`
	ResMap              map[string]string `protobuf:"bytes,3,rep,name=res_map,json=resMap,proto3" json:"res_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ApiResourceInfoReply) Reset() {
	*x = ApiResourceInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiResourceInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResourceInfoReply) ProtoMessage() {}

func (x *ApiResourceInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResourceInfoReply.ProtoReflect.Descriptor instead.
func (*ApiResourceInfoReply) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResourceInfoReply) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *ApiResourceInfoReply) GetApiResourceListJson() []string {
	if x != nil {
		return x.ApiResourceListJson
	}
	return nil
}

func (x *ApiResourceInfoReply) GetResMap() map[string]string {
	if x != nil {
		return x.ResMap
	}
	return nil
}

type ClusterInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClusterInfoReply) Reset() {
	*x = ClusterInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoReply) ProtoMessage() {}

func (x *ClusterInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoReply.ProtoReflect.Descriptor instead.
func (*ClusterInfoReply) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *ClusterInfoReply) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ClusterInfoReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeployResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec      *ResourceSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Cr        string        `protobuf:"bytes,3,opt,name=cr,proto3" json:"cr,omitempty"`
	Order     int32         `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	Action    int32         `protobuf:"varint,5,opt,name=action,proto3" json:"action,omitempty"`
	DefaultNs string        `protobuf:"bytes,6,opt,name=default_ns,json=defaultNs,proto3" json:"default_ns,omitempty"`
	InstName  string        `protobuf:"bytes,7,opt,name=inst_name,json=instName,proto3" json:"inst_name,omitempty"`
	Label     string        `protobuf:"bytes,8,opt,name=label,proto3" json:"label,omitempty"`
	TargetNs  string        `protobuf:"bytes,9,opt,name=target_ns,json=targetNs,proto3" json:"target_ns,omitempty"`
}

func (x *DeployResourceRequest) Reset() {
	*x = DeployResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResourceRequest) ProtoMessage() {}

func (x *DeployResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResourceRequest.ProtoReflect.Descriptor instead.
func (*DeployResourceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *DeployResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeployResourceRequest) GetSpec() *ResourceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DeployResourceRequest) GetCr() string {
	if x != nil {
		return x.Cr
	}
	return ""
}

func (x *DeployResourceRequest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *DeployResourceRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *DeployResourceRequest) GetDefaultNs() string {
	if x != nil {
		return x.DefaultNs
	}
	return ""
}

func (x *DeployResourceRequest) GetInstName() string {
	if x != nil {
		return x.InstName
	}
	return ""
}

func (x *DeployResourceRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DeployResourceRequest) GetTargetNs() string {
	if x != nil {
		return x.TargetNs
	}
	return ""
}

type ResourceSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVer string `protobuf:"bytes,1,opt,name=api_ver,json=apiVer,proto3" json:"api_ver,omitempty"`
	Schema string `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Loaded bool   `protobuf:"varint,3,opt,name=loaded,proto3" json:"loaded,omitempty"`
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *ResourceSpec) GetApiVer() string {
	if x != nil {
		return x.ApiVer
	}
	return ""
}

func (x *ResourceSpec) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *ResourceSpec) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

type DeployResourceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Err       string `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *DeployResourceReply) Reset() {
	*x = DeployResourceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_k8sservice_protocol_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResourceReply) ProtoMessage() {}

func (x *DeployResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_k8sservice_protocol_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResourceReply.ProtoReflect.Descriptor instead.
func (*DeployResourceReply) Descriptor() ([]byte, []int) {
	return file_pkg_k8sservice_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *DeployResourceReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployResourceReply) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeployResourceReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_pkg_k8sservice_protocol_proto protoreflect.FileDescriptor

var file_pkg_k8sservice_protocol_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x38, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72,
	0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x08,
	0x43, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x4d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x47, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x46, 0x6f,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4f, 0x0a, 0x0d, 0x50, 0x6f, 0x64, 0x4c,
	0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x6f, 0x64,
	0x5f, 0x72, 0x61, 0x77, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x6f, 0x64, 0x52, 0x61, 0x77, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x4a, 0x0a, 0x12, 0x41, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1e, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x56, 0x0a, 0x08, 0x47, 0x76, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x34, 0x0a, 0x16, 0x75, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x14, 0x75, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4b, 0x0a,
	0x0f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x47, 0x76, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x67, 0x12, 0x0c,
	0x0a, 0x01, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x76, 0x12, 0x0c, 0x0a, 0x01,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x22, 0x46, 0x0a, 0x0f, 0x41, 0x70,
	0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x33, 0x0a,
	0x16, 0x61, 0x70, 0x69, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x61,
	0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x73,
	0x6f, 0x6e, 0x22, 0x7f, 0x0a, 0x10, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x67, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x67, 0x76, 0x12,
	0x2a, 0x0a, 0x11, 0x61, 0x70, 0x69, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x69, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x22, 0xda, 0x01, 0x0a, 0x14, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x16, 0x61, 0x70, 0x69, 0x5f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x61, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x5f, 0x6d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x41, 0x70, 0x69,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x4d, 0x61, 0x70, 0x1a, 0x39, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x36, 0x0a, 0x10, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf7, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x63, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x6e,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x4e, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f,
	0x6e, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4e, 0x73, 0x22, 0x57, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x22, 0x59, 0x0a, 0x13, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0xe2, 0x05, 0x0a, 0x0e, 0x47, 0x72, 0x70, 0x63, 0x4b,
	0x38, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x07, 0x49, 0x73, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42,
	0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x14, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a,
	0x15, 0x2e, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x47, 0x56, 0x52, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x10, 0x2e,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x47, 0x76, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x09, 0x2e, 0x47, 0x76, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x12,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x41, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x3d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x64, 0x4c, 0x6f, 0x67, 0x12, 0x0e,
	0x2e, 0x50, 0x6f, 0x64, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x4a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x1a, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x52, 0x44,
	0x46, 0x6f, 0x72, 0x12, 0x11, 0x2e, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0x09, 0x2e, 0x43, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x46, 0x6f, 0x72, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2f,
	0x6b, 0x38, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_k8sservice_protocol_proto_rawDescOnce sync.Once
	file_pkg_k8sservice_protocol_proto_rawDescData = file_pkg_k8sservice_protocol_proto_rawDesc
)

func file_pkg_k8sservice_protocol_proto_rawDescGZIP() []byte {
	file_pkg_k8sservice_protocol_proto_rawDescOnce.Do(func() {
		file_pkg_k8sservice_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_k8sservice_protocol_proto_rawDescData)
	})
	return file_pkg_k8sservice_protocol_proto_rawDescData
}

var file_pkg_k8sservice_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_k8sservice_protocol_proto_goTypes = []interface{}{
	(*CrdReply)(nil),               // 0: CrdReply
	(*GetPodContainersReply)(nil),  // 1: GetPodContainersReply
	(*GetDescribeForReply)(nil),    // 2: GetDescribeForReply
	(*PodLogRequest)(nil),          // 3: PodLogRequest
	(*AllNamespacesReply)(nil),     // 4: AllNamespacesReply
	(*GvrReply)(nil),               // 5: GvrReply
	(*FetchGvrRequest)(nil),        // 6: FetchGvrRequest
	(*ApiResourceList)(nil),        // 7: ApiResourceList
	(*ApiResourceEntry)(nil),       // 8: ApiResourceEntry
	(*ApiResourceInfoReply)(nil),   // 9: ApiResourceInfoReply
	(*ClusterInfoReply)(nil),       // 10: ClusterInfoReply
	(*DeployResourceRequest)(nil),  // 11: DeployResourceRequest
	(*ResourceSpec)(nil),           // 12: ResourceSpec
	(*DeployResourceReply)(nil),    // 13: DeployResourceReply
	nil,                            // 14: ApiResourceInfoReply.ResMapEntry
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
	(*wrapperspb.BoolValue)(nil),   // 16: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 17: google.protobuf.StringValue
}
var file_pkg_k8sservice_protocol_proto_depIdxs = []int32{
	14, // 0: ApiResourceInfoReply.res_map:type_name -> ApiResourceInfoReply.ResMapEntry
	12, // 1: DeployResourceRequest.spec:type_name -> ResourceSpec
	15, // 2: GrpcK8sService.IsValid:input_type -> google.protobuf.Empty
	11, // 3: GrpcK8sService.DeployResource:input_type -> DeployResourceRequest
	15, // 4: GrpcK8sService.GetClusterInfo:input_type -> google.protobuf.Empty
	16, // 5: GrpcK8sService.FetchAllApiResources:input_type -> google.protobuf.BoolValue
	6,  // 6: GrpcK8sService.FetchGVRInstances:input_type -> FetchGvrRequest
	15, // 7: GrpcK8sService.FetchAllNamespaces:input_type -> google.protobuf.Empty
	3,  // 8: GrpcK8sService.GetPodLog:input_type -> PodLogRequest
	17, // 9: GrpcK8sService.GetPodContainers:input_type -> google.protobuf.StringValue
	15, // 10: GrpcK8sService.GetClusterName:input_type -> google.protobuf.Empty
	8,  // 11: GrpcK8sService.GetCRDFor:input_type -> ApiResourceEntry
	17, // 12: GrpcK8sService.GetDescribeFor:input_type -> google.protobuf.StringValue
	16, // 13: GrpcK8sService.IsValid:output_type -> google.protobuf.BoolValue
	13, // 14: GrpcK8sService.DeployResource:output_type -> DeployResourceReply
	10, // 15: GrpcK8sService.GetClusterInfo:output_type -> ClusterInfoReply
	9,  // 16: GrpcK8sService.FetchAllApiResources:output_type -> ApiResourceInfoReply
	5,  // 17: GrpcK8sService.FetchGVRInstances:output_type -> GvrReply
	4,  // 18: GrpcK8sService.FetchAllNamespaces:output_type -> AllNamespacesReply
	17, // 19: GrpcK8sService.GetPodLog:output_type -> google.protobuf.StringValue
	1,  // 20: GrpcK8sService.GetPodContainers:output_type -> GetPodContainersReply
	17, // 21: GrpcK8sService.GetClusterName:output_type -> google.protobuf.StringValue
	0,  // 22: GrpcK8sService.GetCRDFor:output_type -> CrdReply
	2,  // 23: GrpcK8sService.GetDescribeFor:output_type -> GetDescribeForReply
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_k8sservice_protocol_proto_init() }
func file_pkg_k8sservice_protocol_proto_init() {
	if File_pkg_k8sservice_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_k8sservice_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPodContainersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDescribeForReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllNamespacesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GvrReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchGvrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiResourceList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiResourceEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiResourceInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_k8sservice_protocol_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployResourceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_k8sservice_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_k8sservice_protocol_proto_goTypes,
		DependencyIndexes: file_pkg_k8sservice_protocol_proto_depIdxs,
		MessageInfos:      file_pkg_k8sservice_protocol_proto_msgTypes,
	}.Build()
	File_pkg_k8sservice_protocol_proto = out.File
	file_pkg_k8sservice_protocol_proto_rawDesc = nil
	file_pkg_k8sservice_protocol_proto_goTypes = nil
	file_pkg_k8sservice_protocol_proto_depIdxs = nil
}
